repos:
- repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: 'v5.0.0'
  hooks:
  - id: 'no-commit-to-branch'
    fail_fast: true
  - id: 'check-case-conflict'
  - id: 'check-merge-conflict'
    args: ['--assume-in-merge']
  - id: 'end-of-file-fixer'
  - id: 'mixed-line-ending'
  - id: 'trailing-whitespace'
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.7
  hooks:
  - id: clang-format


- repo: 'local'
  hooks:
  - id: 'meson-test'
    name: 'meson-test'
    entry: 'meson test -C 2024/build --print-errorlogs'
    language: 'system'
    always_run: true
    pass_filenames: false
